version: '2'
services:
    proxy:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ../:/var/www/site
        ports:
            - "0.0.0.0:80:80"
        expose: 
            - "80"
        networks:
            - docker-proxy-net
networks:
  docker-proxy-net:
    driver: bridge