#!/usr/bin/env bash

SITE_FILE="../sites.yml"
if [ ! -f $SITE_FILE ]; then
    printf "You should create a sites.yml file (copy sites-example.yml)\nUsing sites-example.yml now:\n"
    SITE_FILE="../sites-example.yml"
fi

parse_yaml() {
   local prefix=$2
   local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
   sed -ne "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
   awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
	 printf("%s[%s]=\"%s\"\n", "SITES", $2, $3);
      }
   }'
}

eval $(parse_yaml $SITE_FILE)

# process arguments "$1", "$2", ... (i.e. "$@")
while getopts ":hpgs" opt; do
    case $opt in
    h) HOSTS=true ;; # Handle -h
    p) PORTS=true ;; # Handle -p argument
    s) SSL=true ;; # Handle -s argument
    g) GEN=true ;; # Handle -g argument
    \?) ERROR=true;; # Handle error: unknown option or missing required argument.
    esac
done

if [ $# -eq 0 ]; then
    echo "./proxy-sites [-h hosts] [-p ports] [-g generate nginx confs] [-s generate ssl certs]"
    exit 1
fi

if [ "$GEN" ]; then
    echo "⏳ Generating nginx configuration for sites..."
    for i in "${!SITES[@]}"
    do
      [ $i -eq 80 ] && continue
      NGINX_FILE="../nginx-sites/nginx.${SITES[$i]}.conf"

      rm -f $NGINX_FILE
      touch $NGINX_FILE
      CONF_FILE='../nginx.site.conf'
      NPM_FILE='../npm.script.template'

      # If the site domain starts with local, use local conf instead of site conf
      if [[ ${SITES[$i]} == "local"* ]]; then
        CONF_FILE='../nginx.local.conf'

        # Also, generate a npm script
        NPM_SCRIPT="../npm-scripts/npm.proxy-up.${SITES[$i]}.sh"
        cat "${NPM_FILE}" > $NPM_SCRIPT
        chmod +x $NPM_SCRIPT

        sed -i'.bak' "s/SITE/${SITES[$i]}/g;" $NPM_SCRIPT
        sed -i'.bak' "s/PORT/$i/g;" $NPM_SCRIPT
        rm "${NPM_SCRIPT}.bak"
      fi

      cat "${CONF_FILE}" > $NGINX_FILE

      sed -i'.bak' "s/SITE/${SITES[$i]}/g;" $NGINX_FILE
      sed -i'.bak' "s/PORT/$i/g;" $NGINX_FILE
      rm "${NGINX_FILE}.bak"

    done
    echo "✅ updated /nginx-sites/; ./proxy-up again if you ran this via proxy-sites -n"
    exit 1
fi

if [ "$SSL" ]; then
    echo "⏳ Generating ssl certs for sites..."
    for i in "${!SITES[@]}"
    do
      [ $i -eq 80 ] && continue
      
      # Now create ssl certs for each site
      openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 365 -nodes -subj "/CN=${SITES[$i]}" 2>/dev/null
      
      # If key file exists, change the name of it.
      if [ -f key.pem ]; then
        mv key.pem "../ssl-certs/${SITES[$i]}-key.pem"
      fi

      # if cert file exists, change the name of it.
      if [ -f cert.pem ]; then
        mv cert.pem "../ssl-certs/${SITES[$i]}-cert.pem"
      fi

    done
    echo "✅ updated /ssl-certs/; ./proxy-up again if you ran this via proxy-sites -s"
    exit 1
fi

if [ "$HOSTS" ] && [ ! $(whoami) == "root" ]; then
    echo "🟠 Need to run as root to edit hosts file: sudo ./proxy-sites -h"
    exit 1
fi

if [ "$HOSTS" ]; then
    echo "⏳ Generating /etc/hosts edits based on sites.yml..."
    HOSTS_FILE="/etc/hosts"
    START=$(echo "# PROXYLOCAL START")
    END=$(echo "# PROXYLOCAL END")

    # delete first
    sudo sed -i'' -e "/${START}/,/${END}/d" "${HOSTS_FILE}"

    # make sure hosts file has new line at end of file
    echo "${HOSTS_FILE}" | while read f; do tail -n1 $f | read -r _ || echo >> $f; done

    # make the lines
    CONF="${START}\n"
    for i in "${!SITES[@]}"
    do
      CONF="${CONF}$(printf "127.0.0.1     ${SITES[$i]} socket.${SITES[$i]}\n")\n"
    done
    CONF="${CONF}${END}"

    # add to hosts
    sudo printf "${CONF}" >> "${HOSTS_FILE}"

    echo "✅ updated /etc/hosts/"
fi

if [ "$PORTS" ]; then
    for i in "${!SITES[@]}"
    do
      echo "localhost:$i   ${SITES[$i]}"
    done
fi